#
# Copyright 2017 George Belden
# 
# This file is part of Zenith.
# 
# Zenith is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# Zenith is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# Zenith. If not, see <http://www.gnu.org/licenses/>.
#

spring:
  profiles:
    active: mnist

---

spring:
  profiles: xor

network:
  layers:
    input: 2
    # The hidden layer takes a comma-separated list of integers representing the number of neurons per hidden layer
    hidden: 3
    output: 1
  bias:
    add: true
    weight: 1.0
  trainingSamples:
    count: 10000
  testSamples:
    count: 100
  learningRate: 0.1

problem:
  type: REGRESSION

---

spring:
  profiles: mnist

network:
  layers:
    input: 784
    # The hidden layer takes a comma-separated list of integers representing the number of neurons per hidden layer
    hidden: 392,196
    output: 10
  bias:
    add: true
    weight: 1.0
  trainingSamples:
    count: 100
  testSamples:
    count: 100
  learningRate: 0.1

problem:
  type: CLASSIFICATION

task:
  mnist:
    directory:
      trainingImages: /Users/george/Desktop/MNIST/train-images-idx3-ubyte/train-images.idx3-ubyte
      trainingLabels: /Users/george/Desktop/MNIST/train-labels-idx1-ubyte/train-labels.idx1-ubyte
      testImages: /Users/george/Desktop/MNIST/t10k-images-idx3-ubyte/t10k-images.idx3-ubyte
      testLabels: /Users/george/Desktop/MNIST/t10k-labels-idx1-ubyte/t10k-labels.idx1-ubyte
