#
# Copyright 2017 George Belden
# 
# This file is part of Zenith.
# 
# Zenith is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# Zenith is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# Zenith. If not, see <http://www.gnu.org/licenses/>.
#

spring:
  profiles:
    active: zodiac408
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Zenith
logging:
  level:
    com:
      ciphertool:
        zenith:
          neural:
            generate: INFO

mongodb:
  parallelScan:
    batchSize: 2500
    numCursors: 25

# ---------------------------------------
# Spring Concurrency Properties
# ---------------------------------------
# The taskExecutor.poolSize.override property can be set to override the number of threads
# (defaults to the number of available cores of the system)
taskExecutor:
  queueCapacity: 1000000
  poolSize:
    #override:

collection:
  letter:
    ngram:
      with:
        spaces:
          name: letterNGrams_withSpaces
      without:
        spaces:
          name: letterNGrams_withoutSpaces

---

spring:
  profiles: xor

network:
  inputLayerNeurons: 2
  # The hidden layer takes a comma-separated list of integer:function value pairs representing the number of neurons per hidden layer followed by the activation function type
  hiddenLayers: 3:LEAKY_RELU
  outputLayerNeurons: 1
  initializationType: UNIFORM
  biasWeight: 1.0
  epochs: 1
  batchSize: 1
  inputFileName:
  outputFileName: /Users/george/Desktop/network-xor.json

training:
  weightDecayPercent: 0.0
  learningRate: 0.1
  trainingSampleCount: 10000
  testSampleCount: 1000

---

spring:
  profiles: mnist

network:
  inputLayerNeurons: 784
  # The hidden layer takes a comma-separated list of integer:function value pairs representing the number of neurons per hidden layer followed by the activation function type
  hiddenLayers: 1000:LEAKY_RELU
  outputLayerNeurons: 10
  initializationType: UNIFORM
  biasWeight: 1.0
  epochs: 1
  batchSize: 1
  inputFileName:
  outputFileName: /Users/george/Desktop/network-mnist.json

training:
  weightDecayPercent: 0.0
  learningRate: 0.01
  trainingSampleCount: 60000
  testSampleCount: 10000

task:
  mnist:
    directory:
      trainingImages: /Users/george/Desktop/MNIST/train-images-idx3-ubyte/train-images.idx3-ubyte
      trainingLabels: /Users/george/Desktop/MNIST/train-labels-idx1-ubyte/train-labels.idx1-ubyte
      testImages: /Users/george/Desktop/MNIST/t10k-images-idx3-ubyte/t10k-images.idx3-ubyte
      testLabels: /Users/george/Desktop/MNIST/t10k-labels-idx1-ubyte/t10k-labels.idx1-ubyte

---

spring:
  profiles: zodiac408

network:
  # 391 positions of 26 possible letters each
  inputLayerNeurons: 10166
  # The hidden layer takes a comma-separated list of integer:function value pairs representing the number of neurons per hidden layer followed by the activation function type
  hiddenLayers: 5000:LEAKY_RELU,2500:LEAKY_RELU
  outputLayerNeurons: 4
  initializationType: UNIFORM
  biasWeight: 1.0
  epochs: 1
  batchSize: 1
  inputFileName: #/Users/george/Desktop/network-zodiac408-20180512-015409.json
  outputFileName: /Users/george/Desktop/network-zodiac408.json
  continueTraining: true

training:
  iterationsBetweenSaves: 1000
  weightDecayPercent: 0.0
  learningRate: 0.001
  trainingSampleCount: 10000
  testSampleCount: 2000

task:
  zodiac408:
    sourceDirectory: /Users/george/Desktop/zenith-transformed
