#
# Copyright 2017 George Belden
# 
# This file is part of Zenith.
# 
# Zenith is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# Zenith is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# Zenith. If not, see <http://www.gnu.org/licenses/>.
#

cipher:
  name: zodiac408

# ---------------------------------------
# Spring Concurrency Properties
# ---------------------------------------
# The taskExecutor.poolSize.override property can be set to override the number of threads
# (defaults to the number of available cores of the system)
taskExecutor:
  queueCapacity: 1000000
  poolSize:
    #override:

# ---------------------------------------
# LSTM Service Properties
# ---------------------------------------
lstm:
  service-url: http://localhost:5000/probabilities/

# ---------------------------------------
# Markov Model Properties
# ---------------------------------------
markov:
  corpus:
    directory: /Users/george/Desktop/zenith-transformed
  letter:
    order: 5
    include:
      word:
        boundaries: false
  minimum:
    count: 2

#----------------------------------------
# Bayesian Properties
#----------------------------------------
bayes:
  sampler:
    enable-partial-evaluation: false
    unigram-probability-mass-ratio: 0.5
    iterations: 250
    iterateRandomly: false
    letterTypeSampling:
      enabled: false
  annealing:
    temperature:
      max: 10
      min: 1

#----------------------------------------
# MongoDB Properties
#----------------------------------------
spring:
  main:
    web-application-type: NONE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Zenith

mongodb:
  parallelScan:
    batchSize: 2500
    numCursors: 25

# ---------------------------------------
# Thermal Control Properties
# ---------------------------------------
app:
  commands:
    before:
    after:

#----------------------------------------
# Data Properties
#----------------------------------------
collection:
  letter:
    ngram:
      with:
        spaces:
          name: letterNGrams_withSpaces
      without:
        spaces:
          name: letterNGrams_withoutSpaces
  ngram:
    count:
      sum:
        name: nGramCount_levelSums

network:
  input:
    fileName: /Users/george/Desktop/network-zodiac408-20171017-110402.json