#
# Copyright 2017-2019 George Belden
# 
# This file is part of Zenith.
# 
# Zenith is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# Zenith is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# Zenith. If not, see <http://www.gnu.org/licenses/>.
#

cipher:
  name: zodiac340

# ---------------------------------------
# Markov Model Properties
# ---------------------------------------
markov:
  corpus:
    directory: /Users/george/Desktop/zenith-transformed
  letter:
    order: 5

#----------------------------------------
# Bayesian Properties
#----------------------------------------
decipherment:
  sampler:
    iterations: 5000
    iterateRandomly: false
  annealing:
    temperature:
#      max: 8
#      min: 5
#      max: 0.1
#      min: 0.001
      max: 5
      min: 1
  useKnownEvaluator: false
  epochs: 10
  remove-last-row: true
  transposition:
    column-key-string: byfire
    column-key:
    iterations: 1
    key-length-min: 17
    key-length-max: 17

#----------------------------------------
# MongoDB Properties
#----------------------------------------
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Zenith

mongodb:
  parallelScan:
    batchSize: 2500
    numCursors: 25
